name: CICD

on:
  push:
    tags:
      - '*'

env:
  repository_server: registry.cn-guangzhou.aliyuncs.com
  repository_namespaces: 22528850
  repository_images: wechaty-puppet-tiktok-socket
  repository_username: 22528850@qq.com
  repository_password: ${{ secrets.REPOSITORY_PASSWORD }}

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login --username ${{ env.repository_username }} --password ${{ env.repository_password }} ${{ env.repository_server }}
      - run: docker build --pull --rm -f "dockerfile" -t ${{ env.repository_server }}/${{ env.repository_namespaces }}/${{ env.repository_images }} "."
      - run: docker push ${{ env.repository_server }}/${{ env.repository_namespaces }}/${{ env.repository_images }}
